sudo: false

language: node_js
node_js:
  - 10

cache:
  directories:
    - $HOME/.npm

before_install:
  - npm install coveralls

script: "npm run test:coverage"

after_success:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

branches:
  only:
    - master